import { DatabaseForTesting } from './utils'
export const databaseForTesting = DatabaseForTesting.prepare()

describe('Tests using DB', async () => {
  require('test/application/queries/get-actions-by-jeune.query.handler.test.db.ts')
  require('test/application/queries/get-communes-et-departements.query.handler.test.db.ts')
  require('test/application/queries/get-conseiller-by-email.query.handler.test.db.ts')
  require('test/application/queries/get-conseillers-jeune.query.handler.test.db.ts')
  require('test/application/queries/get-detail-action.query.handler.test.db.ts')
  require('test/application/queries/get-detail-conseiller.query.handler.test.db.ts')
  require('test/application/queries/get-detail-jeune.query.handler.test.db.ts')
  require('test/application/queries/get-detail-rendez-vous.query.handler.test.db.ts')
  require('test/application/queries/get-jeunes-by-conseiller.query.handler.test.db.ts')
  require('test/application/queries/get-rendez-vous-conseiller.query.handler.test.db.ts')
  require('test/application/queries/get-rendez-vous-jeune.query.handler.test.db.ts')
  require('test/application/queries/query-getters/get-campagne.query.getter.test.db.ts')
  require('test/infrastructure/clients/invitation-ics.client.test.db.ts')
  require('test/infrastructure/clients/mail-sendinblue.service.test.db.ts')
  require('test/infrastructure/repositories/action-sql.repository.test.db.ts')
  require('test/infrastructure/repositories/agence-sql.repository.test.db.ts')
  require('test/infrastructure/repositories/authentification-sql.repository.test.db.ts')
  require('test/infrastructure/repositories/campagne-sql.repository.test.db.ts')
  require('test/infrastructure/repositories/conseiller-sql.repository.test.db.ts')
  require('test/infrastructure/repositories/evenement-http-sql.repository.test.db.ts')
  require('test/infrastructure/repositories/jeune-sql.repository.test.db.ts')
  require('test/infrastructure/repositories/mail-sql.repository.test.db.ts')
  require('test/infrastructure/repositories/mappers/conseiller.mapper.test.db.ts')
  require('test/infrastructure/repositories/milo-http-sql.repository.test.db.ts')
  require('test/infrastructure/repositories/offre-emploi-http-sql.repository.test.db.ts')
  require('test/infrastructure/repositories/offre-immersion-http-sql.repository.test.db.ts')
  require('test/infrastructure/repositories/offre-service-civique-http.repository.test.db.ts')
  require('test/infrastructure/repositories/planificateur-redis.repository.test.db.ts')
  require('test/infrastructure/repositories/recherche-sql.repository.test.db.ts')
  require('test/infrastructure/repositories/rendez-vous-sql.repository.test.db.ts')
  require('test/infrastructure/repositories/superviseur-sql.repository.test.db.ts')
})
