rules:
  - id: eval-nestjs
  - id: dot-nestjs
  - id: child-process-nestjs
  - id: direct-response-string-nestjs
  - id: marked-nestjs
  - id: direct-response-nestjs
  - id: nestjs-header-xss-disabled
  - id: logger-nestjs
  - id: nestjs-header-cors-any
  - id: tainted-redirect-nestjs
  - id: nestjs-open-redirect
  - id: nodemail-nestjs
  - id: object-assign-nestjs
  - id: fs-nestjs
  - id: papaparse-nestjs
  - id: rimraf-nestjs
  - id: sharp-nestjs
  - id: mikro-orm-nestjs
  - id: typeorm-nestjs
  - id: prisma-orm-nestjs
  - id: axios-url-nestjs
  - id: http-url-nestjs
  - id: got-config-nestjs
  - id: http2-nestjs
  - id: got-url-nestjs
  - id: net-host-nestjs
  - id: http-host-nestjs
  - id: net-url-nestjs
  - id: request-url-nestjs
  - id: node-fetch-nestjs
  - id: request-config-nestjs
  - id: axios-config-nestjs
  - id: libxml-nestjs
  - id: xpath-nestjs