from datasources.action_database_datasource import ActionDatabaseDatasource
from datasources.conseiller_database_datasource import ConseillerDatabaseDatasource
from datasources.jeune_database_datasource import JeuneDatabaseDatasource
from datasources.rendezvous_database_datasource import RendezvousDatabaseDatasource
from firebase.firebase_chat import FirebaseChat
from initialize_db import db
from repositories.action_repository import ActionRepository
from repositories.conseiller_repository import ConseillerRepository
from repositories.jeune_repository import JeuneRepository
from repositories.rendezvous_repository import RendezvousRepository
from use_cases.action_use_case import ActionUseCase
from use_cases.conseiller_use_case import ConseillerUseCase
from use_cases.home_conseiller_use_case import HomeConseillerUseCase
from use_cases.home_jeune_use_case import HomeJeuneUseCase
from use_cases.jeune_use_case import JeuneUseCase
from use_cases.rendezvous_use_case import RendezvousUseCase

firebase_chat = FirebaseChat()

action_database_datasource = ActionDatabaseDatasource(db)
jeune_database_datasource = JeuneDatabaseDatasource(db)
rendezvous_database_datasource = RendezvousDatabaseDatasource(db)
conseiller_database_datasource = ConseillerDatabaseDatasource()

action_repository = ActionRepository(action_database_datasource)
conseiller_repository = ConseillerRepository(conseiller_database_datasource, jeune_database_datasource)
jeune_repository = JeuneRepository(jeune_database_datasource, firebase_chat)
rendezvous_repository = RendezvousRepository(rendezvous_database_datasource)

jeune_use_case = JeuneUseCase(jeune_repository)
conseiller_use_case = ConseillerUseCase(conseiller_repository)
home_jeune_use_case = HomeJeuneUseCase(jeune_repository, action_repository, rendezvous_repository)
home_conseiller_use_case = HomeConseillerUseCase(jeune_repository, action_repository)
action_use_case = ActionUseCase(jeune_repository, action_repository)
rendezvous_use_case = RendezvousUseCase(jeune_repository, conseiller_repository, rendezvous_repository)
