from datasources.action_creator_database_datasource import ActionCreatorDatabaseDatasource
from datasources.action_database_datasource import ActionDatabaseDatasource
from datasources.conseiller_database_datasource import ConseillerDatabaseDatasource
from datasources.jeune_database_datasource import JeuneDatabaseDatasource
from datasources.rendezvous_database_datasource import RendezvousDatabaseDatasource
from initialize_db import db
from repositories.action_creator_repository import ActionCreatorRepository
from repositories.conseiller_repository import ConseillerRepository
from repositories.jeune_repository import JeuneRepository
from repositories.rendezvous_repository import RendezvousRepository
from src.application.queries.get_detail_action_query_handler import GetDetailActionQueryHandler
from src.application.queries.get_detail_offre_emploi_query_handler import GetDetailOffreEmploiQueryHandler

from src.application.queries.get_liste_offres_emploi_query_handler import GetListeOffresEmploiQueryHandler
from src.infrastructure.datasources.offres_emploi_api_datasource import OffresEmploiAPIDatasource
from src.infrastructure.repositories.actions_db_repository import ActionsDbRepository
from src.infrastructure.repositories.offres_emploi_api_repository import OffresEmploiAPIRepository
from src.infrastructure.services.cache.pole_emploi_token_cache import PoleEmploiTokenCache
from src.infrastructure.services.cache.redis_client import RedisClient
from src.infrastructure.services.firebase.firebase_chat import FirebaseChat
from src.infrastructure.services.pole_emploi.pole_emploi_api import PoleEmploiApi
from src.infrastructure.services.pole_emploi.pole_emploi_api_token_network_retriever import \
    PoleEmploiAPITokenNetworkRetriever
from src.infrastructure.services.pole_emploi.pole_emploi_api_token_retriever_cache_decorator import \
    PoleEmploiAPITokenRetrieverCacheDecorator
from use_cases.action_use_case import ActionUseCase
from use_cases.conseiller_use_case import ConseillerUseCase
from use_cases.home_conseiller_use_case import HomeConseillerUseCase
from use_cases.home_jeune_use_case import HomeJeuneUseCase
from use_cases.jeune_use_case import JeuneUseCase
from use_cases.rendezvous_use_case import RendezvousUseCase

firebase_chat = FirebaseChat()
pole_emploi_api_token_retriever = PoleEmploiAPITokenRetrieverCacheDecorator(
    PoleEmploiAPITokenNetworkRetriever(),
    PoleEmploiTokenCache(RedisClient())
)

# Datasource
action_database_datasource = ActionDatabaseDatasource(db)
jeune_database_datasource = JeuneDatabaseDatasource(db)
rendezvous_database_datasource = RendezvousDatabaseDatasource(db)
conseiller_database_datasource = ConseillerDatabaseDatasource()
action_creator_database_datasource = ActionCreatorDatabaseDatasource(db)
offres_emploi_api_datasource = OffresEmploiAPIDatasource(PoleEmploiApi(pole_emploi_api_token_retriever))

# Repositories
actions_db_repository = ActionsDbRepository(action_database_datasource)
conseiller_repository = ConseillerRepository(conseiller_database_datasource, jeune_database_datasource)
jeune_repository = JeuneRepository(jeune_database_datasource, firebase_chat)
rendezvous_repository = RendezvousRepository(rendezvous_database_datasource)
action_creator_repository = ActionCreatorRepository(action_creator_database_datasource)
offres_emploi_api_repository = OffresEmploiAPIRepository(offres_emploi_api_datasource)

# Use cases
jeune_use_case = JeuneUseCase(jeune_repository)
conseiller_use_case = ConseillerUseCase(conseiller_repository, jeune_repository)
home_jeune_use_case = HomeJeuneUseCase(
    jeune_repository, actions_db_repository, rendezvous_repository,
    action_creator_repository
)
home_conseiller_use_case = HomeConseillerUseCase(jeune_repository, actions_db_repository, action_creator_repository)
action_use_case = ActionUseCase(jeune_repository, actions_db_repository)
rendezvous_use_case = RendezvousUseCase(jeune_repository, conseiller_repository, rendezvous_repository)

# Query handlers
get_detail_action_query_handler = GetDetailActionQueryHandler(actions_db_repository)
get_liste_offres_emploi_query_handler = GetListeOffresEmploiQueryHandler(offres_emploi_api_repository)
get_detail_offre_emploi_query_handler = GetDetailOffreEmploiQueryHandler(offres_emploi_api_repository)
